@startuml
skinparam componentStyle rectangle

node "python application" as py{
    rectangle "python application" as pih
    rectangle "python knx_stack.py" as pis
 note as app
python application
uses knx_stack.py as 
- classes
- functions
to talk indirectly to KNX
end note
}

node "knx stack as shared object" as dll{
    rectangle "oc_python.c" as so_pi
    rectangle "knx-stack" as so_obj
 note as N2
oc_python is used as wrapper
to the functionally of the KNX stack
end note
}

pis -- so_pi
pih -- pis
so_pi -- so_obj

footer //python components//
@enduml
