@startuml
skinparam sequenceMessageAlign center

actor       Actor       as Foo1

participant Device as Dev
box "Device Internal" #LightBlue
participant Device2 as Dev2
participant Resource as Resource 
participant "Group Object Table" as GOT
end box

== runtime with s-mode ==

Foo1 -> Dev : interaction with resource "X"
Dev --> Dev2 : s-mode [GroupID, value]


Dev2 -> GOT : Get groupId's for receiving messages
Dev2 <- GOT : GroupId's


group per GroupID [internal POST]
    Dev2 -> Resource :update [value]
end




@enduml