# This is a basic workflow to help you get started with Actions

name: Cmake Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check_code_style"
  cmake_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # secure
          - args: "-DOC_OSCORE_ENABLED=ON"
          # unsecure
          - args: "-DOC_OSCORE_ENABLED=OFF"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,  so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: build
        run: |
          mkdir linuxbuild
          cd linuxbuild
          cmake ../. ${{ matrix.args }} -DBUILD_TESTING=ON
          make all
      - name: test
        run: |
          cd linuxbuild
          ctest --verbose
