# This is a basic workflow to help you get started with Actions

name: Cmake Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check_code_style"
  cmake_linux_secured:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,  so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: cmake build secured
        run: |
          # https://github.com/actions/checkout/issues/81
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          # create the make files in a subfolder
          mkdir linuxbuild
          cd linuxbuild
          cmake ../. -DOC_OSCORE_ENABLED=ON
          make all OSCORE=1
          ./api/unittest/apitest
          ./port/unittest/platformtest
          #./storage_test
          ./messaging/coap/unittest/messagingtest
          ./security/unittest/securitytest
          
  # This workflow contains a single job called "check_code_style"
  cmake_linux_unsecured:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,  so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: cmake build unsecured 
        run: |
          # https://github.com/actions/checkout/issues/81
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          # create the make files in a subfolder
          mkdir linuxbuild_sec
          cd linuxbuild_sec
          cmake ../. -DOC_OSCORE_ENABLED=OFF
          make all OSCORE=0
          ./api/unittest/apitest
          ./port/unittest/platformtest
          #./storage_test
          ./messaging/coap/unittest/messagingtest
