name: doxygen documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: iotivity-lite
      
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KNX-IOT-STACK_SSH_KEY }}
        
      - name: build_documentation
        run: |
          sudo apt-get update -y
          sudo apt-get install doxygen
          doxygen --version
          cd ${{ github.workspace }}/KNX-IOT-STACK/tools
          ./build_doc.sh
          
      - name: copy-docs
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          cd ~/work
          git clone git@github.com:KNX-IOT/:KNX-IOT-doxygen.git
          cd :KNX-IOT-doxygen
          rm -rf docs
          cp -r ${{ github.workspace }}/:KNX-IOT/tools/html .
          #Rename to "docs"
          mv html docs
          
      - name: push-changes
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          cd ~/work/iotivity-lite-doxygen
          git config --global user.name 'KNX-IOT Bot'
          git config --global user.email 'github@knx.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/KNX-IOT/KNX-IOT-STACk"
          git push
