name: doxygen documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: KNX-IOT-STACK
      

        
      - name: build_documentation
        run: |
          sudo apt-get update -y
          sudo apt-get install doxygen
          doxygen --version
          cd ${{ github.workspace }}/KNX-IOT-STACK/tools
          ./build_doc.sh
          
