name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        # python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: install requirements
      run: |
        python3 -m pip install -r ./pythonbinding/requirements.txt
    - name: pylint
      run: |
        pylint --disable=R0801 $(find . -name "*.py" | xargs)
        #pylint -E $(find . -name "*.py" | xargs)
        #pylint -E ./Network/visualNetwork.py
        #pylint -E ./QR/visualQR.py
        
